ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/dotfiles/.bashrc ~/.bashrc
ln -sf ~/dotfiles/.oh-my-zsh ~/.oh-my-zsh
ln -sf ~/dotfiles/.pyenv ~/.pyenv
ln -sf ~/dotfiles/.tmux-reattach-to-user-namespace.conf ~/.tmux-reattach-to-user-namespace.conf
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/.vim ~/.vim
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.vimrc.local ~/.vimrc.local
ln -sf ~/dotfiles/.zshenv ~/.zhenv
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.zshrc-e ~/.zshrc-e
ln -sf ~/dotfiles/.zshrc.pre-oh-my-zsh ~/.zshrc.pre-oh-my-zsh
ln -sf ~/dotfiles/_gvimrc ~/_gvimrc
